// Auto-generated by scripts/normalize-data-json.mjs. Do not edit manually.
import data0 from './color.json';
import data1 from './flower.json';
import data2 from './fortune.json';
import data3 from './moon.json';
import data4 from './stone.json';

const bundledDataMap: Record<string, unknown> = {
  'color': data0,
  'flower': data1,
  'fortune': data2,
  'moon': data3,
  'stone': data4,
};

export default bundledDataMap;
