// Auto-generated by scripts/normalize-data-json.mjs. Do not edit manually.
import data0 from './birthflower.json';
import data1 from './coffee.json';
import data2 from './color.json';
import data3 from './colormean.json';
import data4 from './flower.json';
import data5 from './fortune.json';
import data6 from './horoscope.json';
import data7 from './kanji.json';
import data8 from './moon.json';
import data9 from './oneword.json';
import data10 from './passage.json';
import data11 from './proverb.json';
import data12 from './quote.json';
import data13 from './recipe.json';
import data14 from './sky.json';
import data15 from './starsign.json';
import data16 from './stone.json';
import data17 from './tea.json';

const bundledDataMap: Record<string, unknown> = {
  'birthflower': data0,
  'coffee': data1,
  'color': data2,
  'colormean': data3,
  'flower': data4,
  'fortune': data5,
  'horoscope': data6,
  'kanji': data7,
  'moon': data8,
  'oneword': data9,
  'passage': data10,
  'proverb': data11,
  'quote': data12,
  'recipe': data13,
  'sky': data14,
  'starsign': data15,
  'stone': data16,
  'tea': data17,
};

export default bundledDataMap;
